### ISSUE TITLE
Fix broken `/wj`

### ISSUE THREAD

**Issue by XVilka** [radareorg/radare2#15851]
See https://ci.appveyor.com/project/radareorg/radare2/build/job/ibmo2yjs5580r7a7#L1907 for more output
```
[**]                  db\tools\rax2   OK  343 BR   17 XX    0 FX    1
[BR] /wj
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.t.check (C:\projects\radare2\test\new\node_modules\node-r2r\index.js:874:14)
    at NewRegressions.checkTest (C:\projects\radare2\test\new\node_modules\node-r2r\index.js:693:12)
    at NewRegressions.checkTestResult (C:\projects\radare2\test\new\node_modules\node-r2r\index.js:729:33)
    at C:\projects\radare2\test\new\node_modules\node-r2r\index.js:145:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[BR] /wj
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.t.check (C:\projects\radare2\test\new\node_modules\node-r2r\index.js:874:14)
    at NewRegressions.checkTest (C:\projects\radare2\test\new\node_modules\node-r2r\index.js:693:12)
    at NewRegressions.checkTestResult (C:\projects\radare2\test\new\node_modules\node-r2r\index.js:729:33)
    at C:\projects\radare2\test\new\node_modules\node-r2r\index.js:145:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[BR] /wj
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.t.check (C:\projects\radare2\test\new\node_modules\node-r2r\index.js:874:14)
    at NewRegressions.checkTest (C:\projects\radare2\test\new\node_modules\node-r2r\index.js:693:12)
    at NewRegressions.checkTestResult (C:\projects\radare2\test\new\node_modules\node-r2r\index.js:729:33)
    at C:\projects\radare2\test\new\node_modules\node-r2r\index.js:145:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[BR] /wj
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.t.check (C:\projects\radare2\test\new\node_modules\node-r2r\index.js:874:14)
    at NewRegressions.checkTest (C:\projects\radare2\test\new\node_modules\node-r2r\index.js:693:12)
    at NewRegressions.checkTestResult (C:\projects\radare2\test\new\node_modules\node-r2r\index.js:729:33)
    at C:\projects\radare2\test\new\node_modules\node-r2r\index.js:145:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by radare** [comment]
whats exactly wrong?

<img width="400" alt="Screenshot 2020-01-20 at 09 11 16" src="https://user-images.githubusercontent.com/917142/72732916-d2586c00-3b64-11ea-9d0c-e3ec4d753182.png">

**Comment by x0urc3** [comment]
Seems that /wj didn't return an empty square bracket '[]' if there's no result. JSON.parse() would gave a SyntaxError if given an empty string.

**Comment by c-urly** [comment]
This issue is solved right?
