### ISSUE TITLE
Debian CI builds should add libuv as runtime dependency

### ISSUE THREAD

**Issue by radare** [radareorg/radare2#16589]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.4.0

### Expected behavior

import r2pipe working

### Actual behavior

```
Collecting r2pipe==1.4.2 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/b7/de/15c6bee12323c673ce6771dba3b26d8deb09721763c1ea89656dd91b2255/r2pipe-1.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ncras4ky/r2pipe/setup.py", line 2, in <module>
        import r2pipe
      File "/tmp/pip-build-ncras4ky/r2pipe/r2pipe/__init__.py", line 38, in <module>
        from .open_sync import open
      File "/tmp/pip-build-ncras4ky/r2pipe/r2pipe/open_sync.py", line 14, in <module>
        from .open_base import OpenBase, get_radare_path
      File "/tmp/pip-build-ncras4ky/r2pipe/r2pipe/open_base.py", line 22, in <module>
        from .native import RCore
      File "/tmp/pip-build-ncras4ky/r2pipe/r2pipe/native.py", line 25, in <module>
        lib = CDLL(lib_name)
      File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: libuv.so.1: cannot open shared object file: No such file or directory
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ncras4ky/r2pipe/
The command '/bin/sh -c cd /tmp/ && pip3 install wheel && pip3 install -r requirements.txt' returned a non-zero code: 1
```

### Steps to reproduce the behavior 

* install the deb
* run r2 or import r2pipe

**Comment by radare** [comment]
generalized in https://github.com/radareorg/radare2/issues/16593
