### ISSUE TITLE
java Segfault

### ISSUE THREAD

**Issue by zonkzonk** [radareorg/radare2#1696]
In the java code, while fuzzing I got this core dump. 

```
[X] r_bin_java: Error unable to parse remainder of classfile after Field Attribute: 0.
r_bin_java_default_attr_new: Unable to find the name for 28 index.
r_bin_java_default_attr_new: Unable to find the name for 27 index.
r_bin_java_default_attr_new: Unable to find the name for 34 index.
[X] r_bin_java: Error unable to parse remainder of classfile in Attribute offset (0x4b5) > len  of remaining bytes (0x4b7).
[X] r_bin_java: Error unable to parse remainder of classfile after Field Attribute: 0.
^C

Core was generated by `r2 -e asm.esil = true -qc af;pdf;s main;pd2;&+ V;& /home/zlul/projects/udp-server'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007facab865255 in handle_bb_cf_recursive_descent (anal=0x1d079e0, state=0x1dc4670)
    at /home/zlul/src/radare2/libr/..//libr/anal/p/anal_java.c:243
243                                             bb->jump = bb->jumpbb->addr;
(gdb) bt                                        
#0  0x00007facab865255 in handle_bb_cf_recursive_descent (anal=0x1d079e0, state=0x1dc4670)
    at /home/zlul/src/radare2/libr/..//libr/anal/p/anal_java.c:243
#1  0x00007facab865038 in java_recursive_descent (anal=0x1d079e0, state=0x1dc4670, addr=1103)
    at /home/zlul/src/radare2/libr/..//libr/anal/p/anal_java.c:177
#2  0x00007facab8a12f0 in r_anal_ex_perform_post_anal_bb_cb (anal=0x1d079e0, state=0x1dc4670, addr=1103) at anal_ex.c:69
#3  0x00007facab8a1cbe in r_anal_ex_analysis_driver (anal=0x1d079e0, state=0x1dc4670, addr=979) at anal_ex.c:292
#4  0x00007facab8a19f9 in r_anal_ex_perform_analysis (anal=0x1d079e0, state=0x1dc4670, addr=979) at anal_ex.c:219
#5  0x00007facab866047 in analyze_method (anal=0x1d079e0, fcn=0x1dc37a0, state=0x1dc4670)
    at /home/zlul/src/radare2/libr/..//libr/anal/p/anal_java.c:607
#6  0x00007facab865c1c in analyze_from_code_buffer (anal=0x1d079e0, fcn=0x1dc37a0, addr=979, code_buf=0x1dc45e0 "\273",
    code_length=127) at /home/zlul/src/radare2/libr/..//libr/anal/p/anal_java.c:517
#7  0x00007facab865e91 in analyze_from_code_attr (anal=0x1d079e0, fcn=0x1dc37a0, method=0x1d90680, loadaddr=0)
    at /home/zlul/src/radare2/libr/..//libr/anal/p/anal_java.c:565
#8  0x00007facab8663c1 in java_analyze_fns (anal=0x1d079e0, start=936, end=18446744073709551615, reftype=0, depth=16)
    at /home/zlul/src/radare2/libr/..//libr/anal/p/anal_java.c:698
#9  0x00007facacc42d91 in r_core_anal_fcn (core=0x6069c0 <r>, at=936, from=18446744073709551615, reftype=0, depth=16)
    at anal.c:649
#10 0x00007facacc002df in cmd_anal_fcn (core=0x6069c0 <r>, input=0x1dbd031 "f") at cmd_anal.c:763
#11 0x00007facacc0299e in cmd_anal (data=0x6069c0 <r>, input=0x1dbd031 "f") at cmd_anal.c:1441
#12 0x00007facacc3f4f7 in r_cmd_call (cmd=0x1d30990, input=0x1dbd030 "af") at cmd_api.c:179
#13 0x00007facacc1f6c8 in r_core_cmd_subst_i (core=0x6069c0 <r>, cmd=0x1dbd030 "af") at cmd.c:1366
#14 0x00007facacc1de29 in r_core_cmd_subst (core=0x6069c0 <r>, cmd=0x1dbd030 "af") at cmd.c:919
#15 0x00007facacc20262 in r_core_cmd (core=0x6069c0 <r>, cstr=0x7fffc948ec9d "af;pdf;s main;pd2;&+ V;&", log=0)
    at cmd.c:1572
#16 0x00007facacc20817 in r_core_cmd0 (user=0x6069c0 <r>, cmd=0x7fffc948ec9d "af;pdf;s main;pd2;&+ V;&") at cmd.c:1695
#17 0x0000000000404a60 in main (argc=6, argv=0x7fffc948e398, envp=0x7fffc948e3d0) at radare2.c:669 

x/i $pc
=> 0x7facab865255 <handle_bb_cf_recursive_descent+447>: mov    0x8(%rax),%rdx

in  #9: 
(gdb) p buflen
$1 = -1455110889
```

Greetings
--zlul

zzufargs:
zzuf  -f xor -v -C 1000  -vc -s 1:1000 -r 0.0008 r2 -e 'asm.esil = true' -qc 'af;pdf;s main;pd2;&+ V;&' UDPServer.class

dmesg:
[20101.724488] r2[5373]: segfault at 8 ip 00007f770c035255 sp 00007fff3911ca80 error 4 in libr_anal.so.0.9.9-git[7f770bf94000+2ea000]

**Comment by GRIM2D** [comment]
```bash
$ r2 -v
radare2 0.10.6-git 9999999 @ darwin-x86-64 git.0.10.6-git
commit: HEAD build: 2016-08-29
```
But I receive these errors when trying to disassemble a file
```
[X] r_bin_java: Error unable to parse remainder of classfile after Method Attribute: 0.
[X] r_bin_java: Error unable to parse remainder of classfile in Attribute len (0x6c7473) + offset (0xbb7cec) exceeds length of buffer (0xbb7d00).
```

**Comment by Maijin** [comment]
@GRIM2D Those seems warning to me. Open a separated issue.
