### ISSUE TITLE
Segmentation fault on disassembling icc compiled vim (-O0)

### ISSUE THREAD

**Issue by Cryspia** [radareorg/radare2#17388]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 20.04 x64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 25024 @ linux-x86-64 git.4.4.0-498-g154416c8f <br>commit: 154416c8fd4ce0a399c42e27ba88a0c535e320a0 build: 2020-07-31__18:45:59

### Expected behavior
Finish disassembling and output the result into a file

### Actual behavior
Reported "_Segmentation fault (core dumped)_"

### Steps to reproduce the behavior 
```bash
r2 -Aqc "pdr @@f > vim.asm" vim
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

[vim.zip](https://github.com/radareorg/radare2/files/5008743/vim.zip)
It is vim 8.2.0821 compiled using icc v19.1.1.219 with _-O0_

**Comment by trufae** [comment]
Can you post the crashlog? Also building with asan (sys/sanitize.sh) will show a better error message. it is also probalby that it fails because debian/ubuntu kernels kill processes if they take too much memory.

**Comment by Cryspia** [comment]
> it is also probalby that it fails because debian/ubuntu kernels kill processes if they take too much memory.

The host machine has 128G RAM and the _htop_ monitor showed that the memory usage was below 13G during the entire r2 execution.

> Can you post the crashlog?

I have built the HEAD (78ea6ec) and reran the disassemble command. Here is the log:
```
root@672a4455c130:/output# r2 -Aqc "pdr @@f > vim.asm" vim
=================================================================
==29683==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602005c6c3f3 at pc 0x7f2ee0dfcb28 bp 0x7ffef463dfa0 sp 0x7ffef463df90
READ of size 1 at 0x602005c6c3f3 thread T0
    #0 0x7f2ee0dfcb27 in r_print_hexdump /radare2/libr/util/print.c:1199
    #1 0x7f2edebbc321 in ds_print_meta_infos /radare2/libr/core/disasm.c:3050
    #2 0x7f2edebd2059 in r_core_print_disasm /radare2/libr/core/disasm.c:5469
    #3 0x7f2edea5177a in cmd_print /radare2/libr/core/cmd_print.c:5398
    #4 0x7f2edeb5803c in r_cmd_call /radare2/libr/core/cmd_api.c:329
    #5 0x7f2edea79a49 in r_core_cmd_subst_i /radare2/libr/core/cmd.c:3744
    #6 0x7f2edea71b43 in r_core_cmd_subst /radare2/libr/core/cmd.c:2716
    #7 0x7f2edea9ba9a in run_cmd_depth /radare2/libr/core/cmd.c:6721
    #8 0x7f2edea9c264 in r_core_cmd /radare2/libr/core/cmd.c:6797
    #9 0x7f2edea9cc12 in r_core_cmdf /radare2/libr/core/cmd.c:6937
    #10 0x7f2edea47d15 in pr_bb /radare2/libr/core/cmd_print.c:4106
    #11 0x7f2edea49a99 in func_walk_blocks /radare2/libr/core/cmd_print.c:4332
    #12 0x7f2edea4f6ed in cmd_print /radare2/libr/core/cmd_print.c:5150
    #13 0x7f2edeb5803c in r_cmd_call /radare2/libr/core/cmd_api.c:329
    #14 0x7f2edea7a255 in r_core_cmd_subst_i /radare2/libr/core/cmd.c:3798
    #15 0x7f2edea71b43 in r_core_cmd_subst /radare2/libr/core/cmd.c:2716
    #16 0x7f2edea9ba9a in run_cmd_depth /radare2/libr/core/cmd.c:6721
    #17 0x7f2edea9c264 in r_core_cmd /radare2/libr/core/cmd.c:6797
    #18 0x7f2edea7e620 in r_core_cmd_foreach /radare2/libr/core/cmd.c:4343
    #19 0x7f2edea78e79 in r_core_cmd_subst_i /radare2/libr/core/cmd.c:3687
    #20 0x7f2edea71b43 in r_core_cmd_subst /radare2/libr/core/cmd.c:2716
    #21 0x7f2edea752ff in r_core_cmd_subst_i /radare2/libr/core/cmd.c:3192
    #22 0x7f2edea71b43 in r_core_cmd_subst /radare2/libr/core/cmd.c:2716
    #23 0x7f2edea9ba9a in run_cmd_depth /radare2/libr/core/cmd.c:6721
    #24 0x7f2edea9c264 in r_core_cmd /radare2/libr/core/cmd.c:6797
    #25 0x7f2edea9c5dd in r_core_cmd_lines /radare2/libr/core/cmd.c:6850
    #26 0x7f2ee0c7e796 in run_commands /radare2/libr/main/radare2.c:262
    #27 0x7f2ee0c85e80 in r_main_radare2 /radare2/libr/main/radare2.c:1368
    #28 0x56412bce3659 in main /radare2/binr/radare2/radare2.c:96
    #29 0x7f2ee0a770b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #30 0x56412bce326d in _start (/radare2/binr/radare2/radare2+0x126d)

0x602005c6c3f3 is located 0 bytes to the right of 3-byte region [0x602005c6c3f0,0x602005c6c3f3)
allocated by thread T0 here:
    #0 0x7f2ee10debc8 in malloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10dbc8)
    #1 0x7f2edea5168d in cmd_print /radare2/libr/core/cmd_print.c:5395
    #2 0x7f2edeb5803c in r_cmd_call /radare2/libr/core/cmd_api.c:329
    #3 0x7f2edea79a49 in r_core_cmd_subst_i /radare2/libr/core/cmd.c:3744
    #4 0x7f2edea71b43 in r_core_cmd_subst /radare2/libr/core/cmd.c:2716
    #5 0x7f2edea9ba9a in run_cmd_depth /radare2/libr/core/cmd.c:6721
    #6 0x7f2edea9c264 in r_core_cmd /radare2/libr/core/cmd.c:6797
    #7 0x7f2edea9cc12 in r_core_cmdf /radare2/libr/core/cmd.c:6937
    #8 0x7f2edea47d15 in pr_bb /radare2/libr/core/cmd_print.c:4106
    #9 0x7f2edea49a99 in func_walk_blocks /radare2/libr/core/cmd_print.c:4332
    #10 0x7f2edea4f6ed in cmd_print /radare2/libr/core/cmd_print.c:5150
    #11 0x7f2edeb5803c in r_cmd_call /radare2/libr/core/cmd_api.c:329
    #12 0x7f2edea7a255 in r_core_cmd_subst_i /radare2/libr/core/cmd.c:3798
    #13 0x7f2edea71b43 in r_core_cmd_subst /radare2/libr/core/cmd.c:2716
    #14 0x7f2edea9ba9a in run_cmd_depth /radare2/libr/core/cmd.c:6721
    #15 0x7f2edea9c264 in r_core_cmd /radare2/libr/core/cmd.c:6797
    #16 0x7f2edea7e620 in r_core_cmd_foreach /radare2/libr/core/cmd.c:4343
    #17 0x7f2edea78e79 in r_core_cmd_subst_i /radare2/libr/core/cmd.c:3687
    #18 0x7f2edea71b43 in r_core_cmd_subst /radare2/libr/core/cmd.c:2716
    #19 0x7f2edea752ff in r_core_cmd_subst_i /radare2/libr/core/cmd.c:3192
    #20 0x7f2edea71b43 in r_core_cmd_subst /radare2/libr/core/cmd.c:2716
    #21 0x7f2edea9ba9a in run_cmd_depth /radare2/libr/core/cmd.c:6721
    #22 0x7f2edea9c264 in r_core_cmd /radare2/libr/core/cmd.c:6797
    #23 0x7f2edea9c5dd in r_core_cmd_lines /radare2/libr/core/cmd.c:6850
    #24 0x7f2ee0c7e796 in run_commands /radare2/libr/main/radare2.c:262
    #25 0x7f2ee0c85e80 in r_main_radare2 /radare2/libr/main/radare2.c:1368
    #26 0x56412bce3659 in main /radare2/binr/radare2/radare2.c:96
    #27 0x7f2ee0a770b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-buffer-overflow /radare2/libr/util/print.c:1199 in r_print_hexdump
Shadow bytes around the buggy address:
  0x0c0480b85820: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480b85830: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480b85840: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480b85850: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480b85860: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fd fd
=>0x0c0480b85870: fa fa fd fa fa fa fa fa fa fa fa fa fa fa[03]fa
  0x0c0480b85880: fa fa fd fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480b85890: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480b858a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480b858b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480b858c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==29683==ABORTING
```

**Comment by trufae** [comment]
So it’s an oobread of 1 byte. I dont have 128GB and it would be great to find a reproducer that doestn rewuired 14GB of ram to work.

Debian/ubuntu kernels kills processes that make huge allocations in small time. Im happy to see this is not the problem. So even having 1tb of ram it couod kill a process too. I’ll check the source to blindly find the reason of this oobread

**Comment by Cryspia** [comment]
> I dont have 128GB and it would be great to find a reproducer that doestn rewuired 14GB of ram to work.

I did have tried different projects compiled by different compilers and optimization levels, and segmentation fault errors did happen on several different binaries. Unfortunately, every binary that resulting in an error is pretty large (such as _cstool(capstone)_ and _gcc_), and this _vim_ binary is already a relative small one among them.

According to the measurement from the ```/bin/time -v r2 -Aqc "pdr @@f > vim.asm" vim``` command, the entire process takes a max resident memory of 2,468,700KB. Therefore, I would consider it still possible to regenerate this error on a pc without large RAM installed.

**Comment by gogo2464** [comment]
I have no idea who has solved this issue. In what pull request. This issue has still be solved. You can close it. I have reproduced the error:


```
radare2 -v
radare2 5.0.1-git 25538 @ linux-x86-64 git.5.0.0
commit: 85cce84722708274fce5432174b3d9f2a64df76a build: 2020-12-29__03:05:07

radare2 -Aqc "pdr @@f > vim.asm" vim
Erreur de segmentation


Then I updated radare2:

$ radare2 -v
radare2 5.2.0-git 25780 @ linux-x86-64 git.5.1.1
commit: 4f67157ff5ab9e9f65cdc8b43a3ed2a9ce1f7c6b build: 2021-03-12__20:03:59

$radare2 -Aqc "pdr @@f > vim.asm" vim
$
```
