### ISSUE TITLE
segmentation fault while loading pdb file (idp command)

### ISSUE THREAD

**Issue by DaniloNC** [radareorg/radare2#17976]
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Kali 2020.4 x64
| File format of the file you reverse (mandatory)      | PE + PDB file
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 4.6.0-git 25299 @ linux-x86-64 git.4.4.0-962-gf18e43128                                                                                                                                                                     
| | commit: f18e431287f477ab5bfd8bd031ed250feb4a9dff build: 2020-11-25__16:30:41       

### Expected behavior
The `idp` command would load the information of the pdb file without crashing

### Actual behavior
radare2 closes due to a segmentation fault.

### Steps to reproduce the behavior 
screen session:
https://asciinema.org/a/srBw7d1wjOgnQQTmk7BUGGuTO

target binaries:
[target.zip](https://github.com/radareorg/radare2/files/5599564/target.zip)

### Additional Logs, screenshots, source-code,  configuration dump, ...
[core.zip](https://github.com/radareorg/radare2/files/5599569/core.zip)

**Comment by DaniloNC** [comment]
backtrace

```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007f3f41d16e73 in get_member_print_type (type=0x560d94719410, name=0x7ffd140246b0) at pdb/tpi.c:2107
#2  0x00007f3f415160bd in parse_member (type_info=0x560d94719410, types=0x560d943b3420) at type_pdb.c:47
#3  0x00007f3f4151668d in parse_structure (anal=0x560d939e9900, type=0x560d94719820, types=0x560d943b3420) at type_pdb.c:190
#4  0x00007f3f41516824 in parse_type (anal=0x560d939e9900, type=0x560d94719820, types=0x560d943b3420) at type_pdb.c:237
#5  0x00007f3f41516945 in r_parse_pdb_types (anal=0x560d939e9900, pdb=0x7ffd14024810) at type_pdb.c:269
#6  0x00007f3f41f909c8 in r_core_pdb_info (core=0x7f3f40fad010, file=0x560d93fe8600 "./echo_server_tlsd.pdb", mode=114) at cbin.c:1276
#7  0x00007f3f41f086c0 in cmd_info (data=0x7f3f40fad010, input=0x560d943c757a "db") at cmd_info.c:901
#8  0x00007f3f41fa47af in r_cmd_call (cmd=0x560d93a2d390, input=0x560d943c7560 "idpi*") at cmd_api.c:361
#9  0x00007f3f41f441e1 in r_core_cmd_subst_i (core=0x7f3f40fad010, cmd=0x560d943c7560 "idpi*", colon=0x0, tmpseek=0x7ffd14024ff7) at cmd.c:3834
#10 0x00007f3f41f406e4 in r_core_cmd_subst (core=0x7f3f40fad010, cmd=0x560d943c7560 "idpi*") at cmd.c:2752
#11 0x00007f3f41f514d6 in run_cmd_depth (core=0x7f3f40fad010, cmd=0x560d94305270 "idpi* ./echo_server_tlsd.pdb") at cmd.c:6751
#12 0x00007f3f41f5191b in r_core_cmd (core=0x7f3f40fad010, cstr=0x560d943c74d0 "idpi* ./echo_server_tlsd.pdb", log=0) at cmd.c:6839
#13 0x00007f3f41f522c3 in r_core_cmd_str (core=0x7f3f40fad010, cmd=0x560d943c74d0 "idpi* ./echo_server_tlsd.pdb") at cmd.c:7053
#14 0x00007f3f41f3cd64 in cmd_interpret (data=0x7f3f40fad010, input=0x560d943aec41 "idpi* ./echo_server_tlsd.pdb") at cmd.c:1391
#15 0x00007f3f41fa47af in r_cmd_call (cmd=0x560d93a2d390, input=0x560d943aec40 ".idpi* ./echo_server_tlsd.pdb") at cmd_api.c:361
#16 0x00007f3f41f441e1 in r_core_cmd_subst_i (core=0x7f3f40fad010, cmd=0x560d943aec40 ".idpi* ./echo_server_tlsd.pdb", colon=0x0, tmpseek=0x7ffd14025657) at cmd.c:3834
#17 0x00007f3f41f406e4 in r_core_cmd_subst (core=0x7f3f40fad010, cmd=0x560d943aec40 ".idpi* ./echo_server_tlsd.pdb") at cmd.c:2752
#18 0x00007f3f41f514d6 in run_cmd_depth (core=0x7f3f40fad010, cmd=0x560d943c8680 ".idpi* ./echo_server_tlsd.pdb") at cmd.c:6751
#19 0x00007f3f41f5191b in r_core_cmd (core=0x7f3f40fad010, cstr=0x7ffd14025790 ".idpi* ./echo_server_tlsd.pdb", log=0) at cmd.c:6839
#20 0x00007f3f41f51f19 in r_core_cmdf (core=0x7f3f40fad010, fmt=0x7f3f42062c22 ".idpi* %s") at cmd.c:6979
#21 0x00007f3f41f081e2 in cmd_info (data=0x7f3f40fad010, input=0x560d944eb4e1 "dp ./echo_server_tlsd.pdb") at cmd_info.c:813
#22 0x00007f3f41fa47af in r_cmd_call (cmd=0x560d93a2d390, input=0x560d944eb4e0 "idp ./echo_server_tlsd.pdb") at cmd_api.c:361
#23 0x00007f3f41f441e1 in r_core_cmd_subst_i (core=0x7f3f40fad010, cmd=0x560d944eb4e0 "idp ./echo_server_tlsd.pdb", colon=0x0, tmpseek=0x7ffd14026fd7) at cmd.c:3834
#24 0x00007f3f41f406e4 in r_core_cmd_subst (core=0x7f3f40fad010, cmd=0x560d944eb4e0 "idp ./echo_server_tlsd.pdb") at cmd.c:2752
#25 0x00007f3f41f514d6 in run_cmd_depth (core=0x7f3f40fad010, cmd=0x560d943c7650 "idp ./echo_server_tlsd.pdb ") at cmd.c:6751
#26 0x00007f3f41f5191b in r_core_cmd (core=0x7f3f40fad010, cstr=0x560d939cb2c0 "idp ./echo_server_tlsd.pdb ", log=1) at cmd.c:6839
#27 0x00007f3f41e91765 in r_core_prompt_exec (r=0x7f3f40fad010) at core.c:3013
#28 0x00007f3f41e90f21 in r_core_prompt_loop (r=0x7f3f40fad010) at core.c:2864
#29 0x00007f3f430c9701 in r_main_radare2 (argc=2, argv=0x7ffd14027598) at radare2.c:1414
#30 0x0000560d93940422 in main (argc=2, argv=0x7ffd14027598) at radare2.c:96

```
