### ISSUE TITLE
Double-free on DEX parser

### ISSUE THREAD

**Issue by enovella** [radareorg/radare2#18256]
## Environment

```sh
[01:55 edu@xps ~] >  date
Thu 21 Jan 01:55:51 CET 2021
[01:55 edu@xps ~] >  r2 -v
radare2 5.0.1-git 26823 @ linux-x86-64 git.5.0.0
commit: d8b6f52e1ddccf3a6051335e399fb150f23065a8 build: 2021-01-21__01:51:00
[01:55 edu@xps ~] >  uname -ms
Linux x86_64
```

## Description

```sh
>  r2 classes.dex 
WARNING: No calling convention defined for this file, analysis may be inaccurate.
 -- I didn't say that it was working, I said that it's implemented
[0x00668711]> q
=================================================================
==32010==ERROR: AddressSanitizer: attempting double-free on 0x6060007a4f20 in thread T0:
    #0 0x7f11601c37a8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8)
    #1 0x7f115f9055bc in r_list_delete /home/edu/radare2/libr/util/list.c:107
    #2 0x7f115f905148 in r_list_purge /home/edu/radare2/libr/util/list.c:73
    #3 0x7f115f9052b3 in r_list_free /home/edu/radare2/libr/util/list.c:83
    #4 0x7f1155bd6d07 in object_delete_items /home/edu/radare2/libr/bin/bobj.c:40
    #5 0x7f1155bd72a0 in r_bin_object_free /home/edu/radare2/libr/bin/bobj.c:62
    #6 0x7f1155bd1ce8 in r_bin_file_free /home/edu/radare2/libr/bin/bfile.c:712
    #7 0x7f115f9055bc in r_list_delete /home/edu/radare2/libr/util/list.c:107
    #8 0x7f115f905148 in r_list_purge /home/edu/radare2/libr/util/list.c:73
    #9 0x7f115f9052b3 in r_list_free /home/edu/radare2/libr/util/list.c:83
    #10 0x7f1155b9f8e3 in r_bin_free /home/edu/radare2/libr/bin/bin.c:472
    #11 0x7f1157abca5e in r_core_fini /home/edu/radare2/libr/core/core.c:3035
    #12 0x7f1157abd1c2 in r_core_free /home/edu/radare2/libr/core/core.c:3061
    #13 0x7f115f344ebb in r_main_radare2 /home/edu/radare2/libr/main/radare2.c:1508
    #14 0x563423ea4908 in main /home/edu/radare2/binr/radare2/radare2.c:96
    #15 0x7f115e1c9bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #16 0x563423ea43e9 in _start (/home/edu/radare2/binr/radare2/radare2+0x13e9)

0x6060007a4f20 is located 0 bytes inside of 56-byte region [0x6060007a4f20,0x6060007a4f58)
freed by thread T0 here:
    #0 0x7f11601c37a8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8)
    #1 0x7f115f9ffdc5 in interval_node_free /home/edu/radare2/libr/util/intervaltree.c:110
    #2 0x7f115f9fc822 in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:306
    #3 0x7f115f9fc7a9 in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:304
    #4 0x7f115f9fc80e in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:305
    #5 0x7f115f9fc7a9 in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:304
    #6 0x7f115f9fc80e in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:305
    #7 0x7f115f9fc7a9 in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:304
    #8 0x7f115f9fc7a9 in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:304
    #9 0x7f115f9fc80e in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:305
    #10 0x7f115f9fc80e in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:305
    #11 0x7f115f9fc80e in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:305
    #12 0x7f115f9fc80e in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:305
    #13 0x7f115f9fc7a9 in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:304
    #14 0x7f115f9fc80e in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:305
    #15 0x7f115f9fc80e in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:305
    #16 0x7f115f9fc7a9 in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:304
    #17 0x7f115f9fc7a9 in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:304
    #18 0x7f115f9fc7a9 in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:304
    #19 0x7f115f9fc7a9 in r_rbtree_free /home/edu/radare2/libr/util/rbtree.c:304
    #20 0x7f115f9ffeec in r_interval_tree_fini /home/edu/radare2/libr/util/intervaltree.c:117
    #21 0x7f115360f6d2 in r_anal_free /home/edu/radare2/libr/anal/anal.c:161
    #22 0x7f1157abc83c in r_core_fini /home/edu/radare2/libr/core/core.c:3031
    #23 0x7f1157abd1c2 in r_core_free /home/edu/radare2/libr/core/core.c:3061
    #24 0x7f115f344ebb in r_main_radare2 /home/edu/radare2/libr/main/radare2.c:1508
    #25 0x563423ea4908 in main /home/edu/radare2/binr/radare2/radare2.c:96
    #26 0x7f115e1c9bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)

previously allocated by thread T0 here:
    #0 0x7f11601c3d28 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded28)
    #1 0x7f115f9ffff1 in r_interval_tree_insert /home/edu/radare2/libr/util/intervaltree.c:122
    #2 0x7f1153591668 in meta_set /home/edu/radare2/libr/anal/meta.c:123
    #3 0x7f1153591fb1 in r_meta_set_with_subtype /home/edu/radare2/libr/anal/meta.c:190
    #4 0x7f1153591f09 in r_meta_set /home/edu/radare2/libr/anal/meta.c:181
    #5 0x7f1157c28fda in cmd_meta_others /home/edu/radare2/libr/core/cmd_meta.c:874
    #6 0x7f1157c2a8f9 in cmd_meta /home/edu/radare2/libr/core/cmd_meta.c:1056
    #7 0x7f1157e3ed2d in r_cmd_call /home/edu/radare2/libr/core/cmd_api.c:359
    #8 0x7f1157cf2b61 in r_core_cmd_subst_i /home/edu/radare2/libr/core/cmd.c:4105
    #9 0x7f1157ce72e4 in r_core_cmd_subst /home/edu/radare2/libr/core/cmd.c:3072
    #10 0x7f1157d1f752 in run_cmd_depth /home/edu/radare2/libr/core/cmd.c:7077
    #11 0x7f1157d20537 in r_core_cmd /home/edu/radare2/libr/core/cmd.c:7165
    #12 0x7f1157d21349 in r_core_cmdf /home/edu/radare2/libr/core/cmd.c:7321
    #13 0x7f1157e173b5 in bin_sections /home/edu/radare2/libr/core/cbin.c:2903
    #14 0x7f1157e23dcf in r_core_bin_info /home/edu/radare2/libr/core/cbin.c:4140
    #15 0x7f1157df8d30 in r_core_bin_set_env /home/edu/radare2/libr/core/cbin.c:341
    #16 0x7f1157d2c323 in r_core_file_do_load_for_io_plugin /home/edu/radare2/libr/core/cfile.c:435
    #17 0x7f1157d2e906 in r_core_bin_load /home/edu/radare2/libr/core/cfile.c:652
    #18 0x7f115f3405da in r_main_radare2 /home/edu/radare2/libr/main/radare2.c:1130
    #19 0x563423ea4908 in main /home/edu/radare2/binr/radare2/radare2.c:96
    #20 0x7f115e1c9bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)

SUMMARY: AddressSanitizer: double-free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8) in __interceptor_free
==32010==ABORTING
```

## Test

[classes.dex.zip](https://github.com/radareorg/radare2/files/5846086/classes.dex.zip)

**Comment by trufae** [comment]
uhm my asan is crashing in a different place. but im on it. will release a fix today

**Comment by trufae** [comment]
i cannot reproduce anymore :/ can you retry?

**Comment by enovella** [comment]
Tested and working fine. Thanks
