### ISSUE TITLE
A crash may be triggered during the `aaft` step of `aaa` for a specific file when `bin.cache` is enabled

### ISSUE THREAD

**Issue by starrify** [radareorg/radare2#19006]
## Environment

```sh
# date
Sat Aug 21 06:34:47 PM IST 2021
# r2 -v
radare2 5.3.1 0 @ linux-x86-64 git.5.3.1
commit: unknown build: 2021-06-12__00:39:47
# uname -ms
Linux x86_64
```

## Description

For a specific file (that I would share below), `r2` would crash (segmentation fault) during `aaa` (specifically, at the `aaft` step) if `bin.cache` is enabled. The analysis would succeed, however, if `bin.cache` is not enabled.

### The target file

Said target file comes from the runtime of Erlang/OTP v23.3.4.4 and could be obtained from the below command:
```
$ docker cp $(docker run --rm -d erlang:23.3.4.4-alpine sh -c "sleep 10"):/usr/local/lib/erlang/erts-11.2.2.3/bin/beam.smp .
```

The SHA-256 hash of said file shall be `a461a68db3a7019211f64ca6fc16ba56676f7e874bc5a95b80921a0496342581`. I have also uploaded the file here for your convenience: https://github.com/radareorg/radare2/files/7025986/beam.smp.zip (zipped due to GitHub's restrictions on file extensions)

I have not checked any other file (e.g. the same path from a different version), and thus am unsure whether the same issue may be triggered by other files.

### Triggering the crash

Said crash may be triggered stably (every time) on my machine (details shared above) via the below command:
```
$ r2 -N -e bin.cache=true -c aaa ./beam.smp
```

<details>
<summary>
Click here for the full output, which suggests that the crash happens at the `aaft` step.
</summary>

```
$ r2 -N -e bin.cache=true -c aaa ./beam.smp
WARNING: No calling convention defined for this file, analysis may be inaccurate.
[Warning: set your favourite calling convention in `e anal.cc=?`
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Finding and parsing C++ vtables (avrr)
[Segmentation fault (core dumped)l functions (aaft)
```
</details>

For a stable reproduction that is irrelevant to my own machine, here is the sample command to trigger the issue from within a docker container:
```
$ docker run --rm erlang:23.3.4.4-alpine sh -c "apk update && apk add radare2 && r2 -v && r2 -N -e bin.cache=true -c aaa -q /usr/local/lib/erlang/erts-11.2.2.3/bin/beam.smp && echo foo"
```

<details>
<summary>
Click here for the full output of the above command, which suggests a crash (segmentation fault).
</summary>

```
$ docker run --rm erlang:23.3.4.4-alpine sh -c "apk update && apk add radare2 && r2 -v && r2 -N -e bin.cache=true -c aaa -q /usr/local/lib/erlang/erts-11.2.2.3/bin/beam.smp && echo foo"
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
v3.14.1-64-g22f341e695 [https://dl-cdn.alpinelinux.org/alpine/v3.14/main]
v3.14.1-63-gb2aec05acf [https://dl-cdn.alpinelinux.org/alpine/v3.14/community]
OK: 14940 distinct packages available
(1/5) Installing capstone (4.0.2-r1)
(2/5) Installing xz-libs (5.2.5-r0)
(3/5) Installing libzip (1.7.3-r2)
(4/5) Installing radare2-libs (5.2.1-r0)
(5/5) Installing radare2 (5.2.1-r0)
Executing busybox-1.33.1-r2.trigger
OK: 38 MiB in 27 packages
radare2 5.2.1 134500 @ linux-x86-64 git.
commit: 3af34185383c9a36d39f86f7629b4c1943005f54 build: 2021-04-22__00:36:07
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Segmentation fault (core dumped)
```
</details>

### No crash when not enabling `bin.cache`

It is observed that no crash would happen when `bin.cache` is not enabled. Here is a sample command by removing the `bin.cache` config from the earlier sample command, which now shall finish without a crash:
```
$ docker run --rm erlang:23.3.4.4-alpine sh -c "apk update && apk add radare2 && r2 -v && r2 -N -c aaa -q /usr/local/lib/erlang/erts-11.2.2.3/bin/beam.smp && echo foo"
```

<details>
<summary>
Click here for the full output of the above command, which suggests no crash.
</summary>

```
$ docker run --rm erlang:23.3.4.4-alpine sh -c "apk update && apk add radare2 && r2 -v && r2 -N -c aaa -q /usr/local/lib/erlang/erts-11.2.2.3/bin/beam.smp && echo foo"
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
v3.14.1-64-g22f341e695 [https://dl-cdn.alpinelinux.org/alpine/v3.14/main]
v3.14.1-63-gb2aec05acf [https://dl-cdn.alpinelinux.org/alpine/v3.14/community]
OK: 14940 distinct packages available
(1/5) Installing capstone (4.0.2-r1)
(2/5) Installing xz-libs (5.2.5-r0)
(3/5) Installing libzip (1.7.3-r2)
(4/5) Installing radare2-libs (5.2.1-r0)
(5/5) Installing radare2 (5.2.1-r0)
Executing busybox-1.33.1-r2.trigger
OK: 38 MiB in 27 packages
radare2 5.2.1 134500 @ linux-x86-64 git.
commit: 3af34185383c9a36d39f86f7629b4c1943005f54 build: 2021-04-22__00:36:07
Warning: run r2 with -e bin.cache=true to fix relocations in disassembly
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
Register wasn't found at the given delta
foo
```
</details>

### Other revisions

I have also quickly checked other revisions by launching different VMs or by building `radare2` from source code on my machine. All my attempts so far resulted in the same crash. Specifically:
- The official package at v5.4.0 from Alpine (edge) and my local build at a60415275 (the most recent commit as I see) could still trigger this issue, which suggests that it is not an issue that has been recently fixed.
- My local builds at tag 5.2.1, 4.5.1, and 3.9.0 could all trigger this issue, which suggests that it is not an issue that was recently introduced.

**Comment by trufae** [comment]
For context:

```
[x] Analyze function calls (aac)
[ ] Analyze len bytes of instructions for reference[x] Analyze len bytes of instructions for references (aar)
[x] Finding and parsing C++ vtables (avrr)
[=================================================================
==67146==ERROR: AddressSanitizer: negative-size-param: (size=-4294967287)
    #0 0x10ff5e23d in __asan_memcpy+0x14d (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4723d)
    #1 0x1004af078 in r_io_cache_read io_cache.c:212
    #2 0x100487e30 in internal_r_io_read_at io.c:289
    #3 0x100487bbf in r_io_read_at io.c:324
    #4 0x10bc8a036 in internal_esil_mem_read esil.c:239
    #5 0x10bc523f5 in r_anal_esil_mem_read esil.c:289
    #6 0x10bc91968 in esil_poke_n esil.c:2006
    #7 0x10bc78bb9 in esil_poke4 esil.c:2037
    #8 0x10bc5da80 in runword esil.c:3527
    #9 0x10bc5a6fd in r_anal_esil_parse esil.c:3708
    #10 0x10bd1d87a in r_anal_esil_trace_op esil_trace.c:238
    #11 0x108311590 in r_debug_trace_op trace.c:182
    #12 0x106f6713f in r_core_esil_step cmd_anal.c:5208
    #13 0x10792dced in r_core_anal_type_match anal_tp.c:553
    #14 0x10720d355 in cmd_anal_aaft cmd_anal.c:997
    #15 0x1071bd72d in cmd_anal_all cmd_anal.c:10179
    #16 0x10700f01d in cmd_anal cmd_anal.c:11360
    #17 0x1075e829b in r_cmd_call cmd_api.c:354
    #18 0x1070fc457 in r_core_cmd_subst_i cmd.c:4296
    #19 0x1070e4823 in r_core_cmd_subst cmd.c:3194
    #20 0x106fd30fc in run_cmd_depth cmd.c:5243
    #21 0x106fb399c in r_core_cmd cmd.c:5327
    #22 0x106f5a1ce in r_core_cmd0 cmd.c:5484
    #23 0x1071c2f8f in cmd_anal_all cmd_anal.c:10425
    #24 0x10700f01d in cmd_anal cmd_anal.c:11360
    #25 0x1075e829b in r_cmd_call cmd_api.c:354
    #26 0x1070fc457 in r_core_cmd_subst_i cmd.c:4296
    #27 0x1070e4823 in r_core_cmd_subst cmd.c:3194
    #28 0x106fd30fc in run_cmd_depth cmd.c:5243
    #29 0x106fb399c in r_core_cmd cmd.c:5327
    #30 0x106f37502 in r_core_prompt_exec core.c:3267
    #31 0x106f36728 in r_core_prompt_loop core.c:3087
    #32 0x10fe8a180 in r_main_radare2 radare2.c:1456
    #33 0x1002554b5 in main radare2.c:96
    #34 0x7fff695d5cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

0x60200140ed57 is located 2 bytes to the right of 5-byte region [0x60200140ed50,0x60200140ed55)
allocated by thread T0 here:
    #0 0x10ff60552 in wrap_calloc+0xa2 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x49552)
    #1 0x1004ad336 in r_io_cache_write io_cache.c:164
    #2 0x100488f4f in r_io_write_at io.c:384
    #3 0x10bc8ee93 in internal_esil_mem_write esil.c:326
    #4 0x10bc534f1 in r_anal_esil_mem_write esil.c:381
    #5 0x10bc92189 in esil_poke_n esil.c:2014
    #6 0x10bc78bb9 in esil_poke4 esil.c:2037
    #7 0x10bc5da80 in runword esil.c:3527
    #8 0x10bc5a6fd in r_anal_esil_parse esil.c:3708
    #9 0x10bd1d87a in r_anal_esil_trace_op esil_trace.c:238
    #10 0x108311590 in r_debug_trace_op trace.c:182
    #11 0x106f6713f in r_core_esil_step cmd_anal.c:5208
    #12 0x10792dced in r_core_anal_type_match anal_tp.c:553
    #13 0x10720d355 in cmd_anal_aaft cmd_anal.c:997
    #14 0x1071bd72d in cmd_anal_all cmd_anal.c:10179
    #15 0x10700f01d in cmd_anal cmd_anal.c:11360
    #16 0x1075e829b in r_cmd_call cmd_api.c:354
    #17 0x1070fc457 in r_core_cmd_subst_i cmd.c:4296
    #18 0x1070e4823 in r_core_cmd_subst cmd.c:3194
    #19 0x106fd30fc in run_cmd_depth cmd.c:5243
    #20 0x106fb399c in r_core_cmd cmd.c:5327
    #21 0x106f5a1ce in r_core_cmd0 cmd.c:5484
    #22 0x1071c2f8f in cmd_anal_all cmd_anal.c:10425
    #23 0x10700f01d in cmd_anal cmd_anal.c:11360
    #24 0x1075e829b in r_cmd_call cmd_api.c:354
    #25 0x1070fc457 in r_core_cmd_subst_i cmd.c:4296
    #26 0x1070e4823 in r_core_cmd_subst cmd.c:3194
    #27 0x106fd30fc in run_cmd_depth cmd.c:5243
    #28 0x106fb399c in r_core_cmd cmd.c:5327
    #29 0x106f37502 in r_core_prompt_exec core.c:3267

SUMMARY: AddressSanitizer: negative-size-param (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x4723d) in __asan_memcpy+0x14d
==67146==ABORTING
zsh: abort      r2 -e bin.cache=1 ~/Downloads/beam.smp
$
```
