### ISSUE TITLE
Heap-based overflow in `of` command

### ISSUE THREAD

**Issue by enovella** [radareorg/radare2#19377]
## Environment

```sh
[15:21 edu@xps ~] >  date
Fri  5 Nov 15:21:12 CET 2021
[15:21 edu@xps ~] >  r2 -v
radare2 5.4.3 27386 @ linux-x86-64 git.5.4.2
commit: 7a0412b743aacbef3cd080aade90260c2b2716db build: 2021-11-03__18:47:30
[15:21 edu@xps ~] >  uname -ms
Linux x86_64
```

## Test

```sh
[15:18 edu@xps ~] >  r2 apk:///tmp/com.mobileiron.apk 
 -- Rename a function using the 'afr <newname> @ <offset>' command.
[0x016cd3ec]> i
fd       8
file     ?
size     0x836c8
humansz  525.7K
mode     r-x
format   dex
iorw     false
block    0x100
type     DEX CLASS
arch     dalvik
baddr    0x19ecbf0
binsz    538312
bintype  class
bits     32
canary   false
retguard false
class    035
crypto   false
endian   little
havecode true
laddr    0x0
lang     dalvik
linenum  false
lsyms    false
machine  Dalvik VM
nx       false
os       linux
pic      false
relocs   false
sanitize false
static   true
stripped false
subsys   java
va       true
sha1  12-538292c  e970be6e779b07ddfde2b32a208b8d54b19ec042
adler32  12-538312c  2ab562dc

[0x016cd3ec]> of
=================================================================
==1267==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602008b65bb3 at pc 0x7f96ae5dd2af bp 0x7ffffd40c870 sp 0x7ffffd40c860
READ of size 1 at 0x602008b65bb3 thread T0
    #0 0x7f96ae5dd2ae in r_str_trim_head_ro /home/edu/radare2/libr/util/str_trim.c:87
    #1 0x7f96a439f055 in cmd_open /home/edu/radare2/libr/core/cmd_open.c:1734
    #2 0x7f96a45af255 in r_cmd_call /home/edu/radare2/libr/core/cmd_api.c:537
    #3 0x7f96a44828fd in r_core_cmd_subst_i /home/edu/radare2/libr/core/cmd.c:4392
    #4 0x7f96a4475cd5 in r_core_cmd_subst /home/edu/radare2/libr/core/cmd.c:3279
    #5 0x7f96a448c800 in run_cmd_depth /home/edu/radare2/libr/core/cmd.c:5279
    #6 0x7f96a448d537 in r_core_cmd /home/edu/radare2/libr/core/cmd.c:5362
    #7 0x7f96a42334b4 in r_core_prompt_exec /home/edu/radare2/libr/core/core.c:3282
    #8 0x7f96a4231269 in r_core_prompt_loop /home/edu/radare2/libr/core/core.c:3103
    #9 0x7f96adebd5bc in r_main_radare2 /home/edu/radare2/libr/main/radare2.c:1461
    #10 0x5564dab78b4e in main /home/edu/radare2/binr/radare2/radare2.c:96
    #11 0x7f96acd34bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #12 0x5564dab78579 in _start (/home/edu/radare2/binr/radare2/radare2+0x1579)

0x602008b65bb3 is located 0 bytes to the right of 3-byte region [0x602008b65bb0,0x602008b65bb3)
allocated by thread T0 here:
    #0 0x7f96aed98538 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x77538)
    #1 0x7f96a4474c94 in r_core_cmd_subst /home/edu/radare2/libr/core/cmd.c:3189
    #2 0x7f96a448c800 in run_cmd_depth /home/edu/radare2/libr/core/cmd.c:5279
    #3 0x7f96a448d537 in r_core_cmd /home/edu/radare2/libr/core/cmd.c:5362
    #4 0x7f96a42334b4 in r_core_prompt_exec /home/edu/radare2/libr/core/core.c:3282
    #5 0x7f96a4231269 in r_core_prompt_loop /home/edu/radare2/libr/core/core.c:3103
    #6 0x7f96adebd5bc in r_main_radare2 /home/edu/radare2/libr/main/radare2.c:1461
    #7 0x5564dab78b4e in main /home/edu/radare2/binr/radare2/radare2.c:96
    #8 0x7f96acd34bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/edu/radare2/libr/util/str_trim.c:87 in r_str_trim_head_ro
Shadow bytes around the buggy address:
  0x0c0481164b20: fa fa 04 fa fa fa 03 fa fa fa 04 fa fa fa 03 fa
  0x0c0481164b30: fa fa 04 fa fa fa 03 fa fa fa 04 fa fa fa 05 fa
  0x0c0481164b40: fa fa 04 fa fa fa 04 fa fa fa 03 fa fa fa 02 fa
  0x0c0481164b50: fa fa 03 fa fa fa 04 fa fa fa 04 fa fa fa 04 fa
  0x0c0481164b60: fa fa 03 fa fa fa fd fa fa fa fd fa fa fa 03 fa
=>0x0c0481164b70: fa fa 03 fa fa fa[03]fa fa fa 01 fa fa fa fa fa
  0x0c0481164b80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0481164b90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0481164ba0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0481164bb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0481164bc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1267==ABORTING
```

```sh
[15:22 edu@xps ~] >  r2 /bin/ls
Warning: run r2 with -e bin.cache=true to fix relocations in disassembly
 -- This is fine.
[0x00005850]> of
=================================================================
==2414==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000feb13 at pc 0x7f7228c622af bp 0x7ffd8c9eae70 sp 0x7ffd8c9eae60
READ of size 1 at 0x6020000feb13 thread T0
    #0 0x7f7228c622ae in r_str_trim_head_ro /home/edu/radare2/libr/util/str_trim.c:87
    #1 0x7f721ea24055 in cmd_open /home/edu/radare2/libr/core/cmd_open.c:1734
    #2 0x7f721ec34255 in r_cmd_call /home/edu/radare2/libr/core/cmd_api.c:537
    #3 0x7f721eb078fd in r_core_cmd_subst_i /home/edu/radare2/libr/core/cmd.c:4392
    #4 0x7f721eafacd5 in r_core_cmd_subst /home/edu/radare2/libr/core/cmd.c:3279
    #5 0x7f721eb11800 in run_cmd_depth /home/edu/radare2/libr/core/cmd.c:5279
    #6 0x7f721eb12537 in r_core_cmd /home/edu/radare2/libr/core/cmd.c:5362
    #7 0x7f721e8b84b4 in r_core_prompt_exec /home/edu/radare2/libr/core/core.c:3282
    #8 0x7f721e8b6269 in r_core_prompt_loop /home/edu/radare2/libr/core/core.c:3103
    #9 0x7f72285425bc in r_main_radare2 /home/edu/radare2/libr/main/radare2.c:1461
    #10 0x55d58975ab4e in main /home/edu/radare2/binr/radare2/radare2.c:96
    #11 0x7f72273b9bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
    #12 0x55d58975a579 in _start (/home/edu/radare2/binr/radare2/radare2+0x1579)

0x6020000feb13 is located 0 bytes to the right of 3-byte region [0x6020000feb10,0x6020000feb13)
allocated by thread T0 here:
    #0 0x7f722941d538 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x77538)
    #1 0x7f721eaf9c94 in r_core_cmd_subst /home/edu/radare2/libr/core/cmd.c:3189
    #2 0x7f721eb11800 in run_cmd_depth /home/edu/radare2/libr/core/cmd.c:5279
    #3 0x7f721eb12537 in r_core_cmd /home/edu/radare2/libr/core/cmd.c:5362
    #4 0x7f721e8b84b4 in r_core_prompt_exec /home/edu/radare2/libr/core/core.c:3282
    #5 0x7f721e8b6269 in r_core_prompt_loop /home/edu/radare2/libr/core/core.c:3103
    #6 0x7f72285425bc in r_main_radare2 /home/edu/radare2/libr/main/radare2.c:1461
    #7 0x55d58975ab4e in main /home/edu/radare2/binr/radare2/radare2.c:96
    #8 0x7f72273b9bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/edu/radare2/libr/util/str_trim.c:87 in r_str_trim_head_ro
Shadow bytes around the buggy address:
  0x0c0480017d10: fa fa 03 fa fa fa 04 fa fa fa 03 fa fa fa 04 fa
  0x0c0480017d20: fa fa 03 fa fa fa 04 fa fa fa 05 fa fa fa 04 fa
  0x0c0480017d30: fa fa 04 fa fa fa 03 fa fa fa 02 fa fa fa 03 fa
  0x0c0480017d40: fa fa 04 fa fa fa 04 fa fa fa 04 fa fa fa 03 fa
  0x0c0480017d50: fa fa fd fa fa fa fd fa fa fa 03 fa fa fa 03 fa
=>0x0c0480017d60: fa fa[03]fa fa fa 01 fa fa fa fa fa fa fa fa fa
  0x0c0480017d70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480017d80: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480017d90: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480017da0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0480017db0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==2414==ABORTING
```

**Comment by trufae** [comment]
A simpler reproducer:

```
[0x00000000]> of
=================================================================
==81150==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000096793 at pc 0x0001068f286e bp 0x7ffee9b7d3e0 sp 0x7ffee9b7d3d8
READ of size 1 at 0x602000096793 thread T0
    #0 0x1068f286d in r_str_trim_head_ro str_trim.c:87
    #1 0x10e5af219 in cmd_open cmd_open.c:1734
    #2 0x10eb3150d in r_cmd_call cmd_api.c:537
    #3 0x10e63431b in r_core_cmd_subst_i cmd.c:4392
    #4 0x10e61b8de in r_core_cmd_subst cmd.c:3279
    #5 0x10e4fdb3c in run_cmd_depth cmd.c:5279
    #6 0x10e4dcf7c in r_core_cmd cmd.c:5362
    #7 0x10e461322 in r_core_prompt_exec core.c:3282
    #8 0x10e460548 in r_core_prompt_loop core.c:3103
    #9 0x1080bc508 in r_main_radare2 radare2.c:1461
    #10 0x10607e395 in main radare2.c:96
    #11 0x7fff72191cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

0x602000096793 is located 0 bytes to the right of 3-byte region [0x602000096790,0x602000096793)
allocated by thread T0 here:
    #0 0x115fb1620 in wrap_strdup+0x200 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x44620)
    #1 0x10e6196a4 in r_core_cmd_subst cmd.c:3189
    #2 0x10e4fdb3c in run_cmd_depth cmd.c:5279
    #3 0x10e4dcf7c in r_core_cmd cmd.c:5362
    #4 0x10e461322 in r_core_prompt_exec core.c:3282
    #5 0x10e460548 in r_core_prompt_loop core.c:3103
    #6 0x1080bc508 in r_main_radare2 radare2.c:1461
    #7 0x10607e395 in main radare2.c:96
    #8 0x7fff72191cc8 in start+0x0 (libdyld.dylib:x86_64+0x1acc8)

SUMMARY: AddressSanitizer: heap-buffer-overflow str_trim.c:87 in r_str_trim_head_ro
Shadow bytes around the buggy address:
```

**Comment by trufae** [comment]
Fixed in master
