### ISSUE TITLE
Heap buffer underflow in marshal.c

### ISSUE THREAD

**Issue by RickdeJager** [radareorg/radare2#19442]
## Environment

```sh
$ date
za 27 nov 2021 14:10:56 CET
$ r2 -v
radare2 5.5.1 27155 @ linux-x86-64 git.5.5.0
commit: 4b39d625ee90199697cb67e60793b2c26a541ab6 build: 2021-11-27__14:06:34
$ uname -ms
Linux x86_64
```

## Description

The `long` decoder can underflow when creating a hex string, resulting in heap corruption. The issue can be triggered by loading the attached crash file with `r2` like so:
```
r2 'heap-buffer-overflow-(WRITE1)-marshal.c:226'
```

### GDB output

I've set a breakpoint at the source line that causes memory corruption:
```
In file: /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/bin/format/pyc/marshal.c
   221 		if (tmp) {
   222 			hexstr[--j] = digist2hex[tmp & 0xf];
   223 		}
   224 
   225 		hexstr[--j] = 'x';
 ► 226 		hexstr[--j] = '0';
   227 		if (neg) {
   228 			hexstr[--j] = '-';
   229 		}
   230 
   231 		ret->data = &hexstr[j];
```
Before the decrement, `j` is already `0`:
```
pwndbg> p j
$1 = 0
```

### ASan report:
```
 r2 'heap-buffer-overflow-(WRITE1)-marshal.c:226'
Undefined type in get_object (0x68)
Undefined type in get_object (0x65)
=================================================================
==122983==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62000004607f at pc 0x7f08aa784e7c bp 0x7ffde1f12e30 sp 0x7ffde1f12e20
WRITE of size 1 at 0x62000004607f thread T0
    #0 0x7f08aa784e7b in get_long_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:226
    #1 0x7f08aa78d047 in get_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:1108
    #2 0x7f08aa78bc21 in get_code_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:947
    #3 0x7f08aa78ce55 in get_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:1063
    #4 0x7f08aa787548 in get_array_object_generic /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:497
    #5 0x7f08aa787b69 in get_tuple_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:545
    #6 0x7f08aa78cd8c in get_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:1051
    #7 0x7f08aa78ba58 in get_code_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:941
    #8 0x7f08aa78ce55 in get_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:1063
    #9 0x7f08aa78e8cf in get_sections_symbols_from_code_objects /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:1221
    #10 0x7f08aa78fe77 in pyc_get_sections_symbols /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/pyc.c:7
    #11 0x7f08aa782e70 in symbols /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/bin_pyc.c:124
    #12 0x7f08aa2e2e72 in r_bin_object_set_items /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/bin/bobj.c:325
    #13 0x7f08aa2df48a in r_bin_object_new /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/bin/bobj.c:168
    #14 0x7f08aa2d4242 in r_bin_file_new_from_buffer /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/bin/bfile.c:560
    #15 0x7f08aa292968 in r_bin_open_buf /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/bin/bin.c:286
    #16 0x7f08aa29379d in r_bin_open_io /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/bin/bin.c:346
    #17 0x7f08ac84e706 in r_core_file_do_load_for_io_plugin /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/core/cfile.c:434
    #18 0x7f08ac85125a in r_core_bin_load /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/core/cfile.c:635
    #19 0x7f08b6e6ca17 in r_main_radare2 /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/main/radare2.c:1176
    #20 0x560eb9f8f937 in main /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/binr/radare2/radare2.c:96
    #21 0x7f08b627c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #22 0x560eb9f8f30d in _start (/home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/binr/radare2/radare2+0x230d)

0x62000004607f is located 1 bytes to the left of 3843-byte region [0x620000046080,0x620000046f83)
allocated by thread T0 here:
    #0 0x7f08b7cf2dc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x7f08aa7849be in get_long_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:202
    #2 0x7f08aa78d047 in get_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:1108
    #3 0x7f08aa78bc21 in get_code_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:947
    #4 0x7f08aa78ce55 in get_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:1063
    #5 0x7f08aa787548 in get_array_object_generic /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:497
    #6 0x7f08aa787b69 in get_tuple_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:545
    #7 0x7f08aa78cd8c in get_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:1051
    #8 0x7f08aa78ba58 in get_code_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:941
    #9 0x7f08aa78ce55 in get_object /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:1063
    #10 0x7f08aa78e8cf in get_sections_symbols_from_code_objects /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:1221
    #11 0x7f08aa78fe77 in pyc_get_sections_symbols /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/pyc.c:7
    #12 0x7f08aa782e70 in symbols /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/bin_pyc.c:124
    #13 0x7f08aa2e2e72 in r_bin_object_set_items /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/bin/bobj.c:325
    #14 0x7f08aa2df48a in r_bin_object_new /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/bin/bobj.c:168
    #15 0x7f08aa2d4242 in r_bin_file_new_from_buffer /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/bin/bfile.c:560
    #16 0x7f08aa292968 in r_bin_open_buf /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/bin/bin.c:286
    #17 0x7f08aa29379d in r_bin_open_io /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/bin/bin.c:346
    #18 0x7f08ac84e706 in r_core_file_do_load_for_io_plugin /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/core/cfile.c:434
    #19 0x7f08ac85125a in r_core_bin_load /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/core/cfile.c:635
    #20 0x7f08b6e6ca17 in r_main_radare2 /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/main/radare2.c:1176
    #21 0x560eb9f8f937 in main /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/binr/radare2/radare2.c:96
    #22 0x7f08b627c0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/rick/courses/ru/SoftwareSecurity/RadareFuzzing/radare2/libr/..//libr/bin/p/../format/pyc/marshal.c:226 in get_long_object
Shadow bytes around the buggy address:
  0x0c4080000bb0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c4080000bc0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c4080000bd0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c4080000be0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c4080000bf0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x0c4080000c00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x0c4080000c10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4080000c20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4080000c30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4080000c40: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4080000c50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==122983==ABORTING
```

## Test
1. Download the attached crash file and unzip it.
2. Create a radare build with ASan
2. open the crash file `r2 'heap-buffer-overflow-(WRITE1)-marshal.c:226'`

## Attachements
[heap-buffer-overflow-(WRITE1)-marshal.c:226.zip](https://github.com/radareorg/radare2/files/7611769/heap-buffer-overflow-.WRITE1.-marshal.c.226.zip)

**Comment by trufae** [comment]
Thanks!
