### ISSUE TITLE
SIGSEV in `r_io_bank_del_map`

### ISSUE THREAD

**Issue by gnif** [radareorg/radare2#19641]
## Environment

```sh
Sun 30 Jan 2022 11:25:04 AEDT
radare2 5.5.4 1 @ linux-x86-64 git.
commit: 1703da75e247871e6fa22d3308551a291dad8f01 build: 2021-12-15__09:25:30
Linux x86_64
```

## Description

Attempting to disassemble a firmware dump from a Phillips P87C51FB results in a segfault

## Test

```gdb
gdb /usr/bin/radare2
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/radare2...
(No debugging symbols found in /usr/bin/radare2)
(gdb) set args -AA -a 80C51 firmware.bin 
(gdb) r
Starting program: /usr/bin/radare2 -AA -a 80C51 trunc.bin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Warning: set your favourite calling convention in `e anal.cc=?`
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] find and analyze function preludes (aap)
[x] Analyze len bytes of instructions for references (aar)
[x] Finding and parsing C++ vtables (avrr)
[x] Finding xrefs in noncode section (e anal.in=io.maps.x)
[x] Analyze value pointers (aav)
[x] Value from 0x00000000 to 0x00004000 (aav)
[x] 0x00000000-0x00004000 in 0x0-0x4000 (aav)
[x] Emulate functions to find computed references (aaef)
[ ] Type matching analysis for all functions (aaft)
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff70b931b in r_io_bank_del_map () from /lib/libr_io.so
(gdb) bt
#0  0x00007ffff70b931b in r_io_bank_del_map () from /lib/libr_io.so
#1  0x00007ffff70b3ac6 in r_io_map_del () from /lib/libr_io.so
#2  0x00007ffff70b3ba4 in r_io_map_del_for_fd () from /lib/libr_io.so
#3  0x00007ffff70b42dc in r_io_desc_del () from /lib/libr_io.so
#4  0x00007ffff70b460c in r_io_desc_close () from /lib/libr_io.so
#5  0x00007ffff5aa7189 in ?? () from /lib/libr_core.so
#6  0x00007ffff5aaea5e in ?? () from /lib/libr_core.so
#7  0x00007ffff5acc9d9 in ?? () from /lib/libr_core.so
#8  0x00007ffff5a8af2f in ?? () from /lib/libr_core.so
#9  0x00007ffff5a8a109 in ?? () from /lib/libr_core.so
#10 0x00007ffff5a8c7a7 in r_core_cmd () from /lib/libr_core.so
#11 0x00007ffff5aa98fd in ?? () from /lib/libr_core.so
#12 0x00007ffff5accd69 in ?? () from /lib/libr_core.so
#13 0x00007ffff5a8af2f in ?? () from /lib/libr_core.so
#14 0x00007ffff5a8c7a7 in r_core_cmd () from /lib/libr_core.so
#15 0x00007ffff5aaa2b2 in ?? () from /lib/libr_core.so
#16 0x00007ffff5accd69 in ?? () from /lib/libr_core.so
#17 0x00007ffff5a8af2f in ?? () from /lib/libr_core.so
#18 0x00007ffff5a8c7a7 in r_core_cmd () from /lib/libr_core.so
#19 0x00007ffff7a5d5a2 in r_main_radare2 () from /lib/libr_main.so
#20 0x00007ffff78a4d0a in __libc_start_main (main=0x5555554008c0, argc=5, argv=0x7fffffffe438, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffe428) at ../csu/libc-start.c:308
#21 0x0000555555400afa in ?? ()
```
[firmware.bin.gz](https://github.com/radareorg/radare2/files/7965049/firmware.bin.gz)

**Comment by trufae** [comment]
This was fixed in master a month ago, can you confirm ?

**Comment by trufae** [comment]
PD: it was already reported and there's a CVE assigned to it
