### ISSUE TITLE
Null Pointer in rasm2.c

### ISSUE THREAD

**Issue by Pikachu1412** [radareorg/radare2#21958]
## TL;DR
we perfom a fuzz on radare2 and find this bug.
When rarch2_list is called, as is not checked to see if it is null.
https://github.com/radareorg/radare2/blob/533aeeb6a31b1f8b4fc7f028df77bbdb62581322/libr/main/rasm2.c#L891
Then the pointer is referenced at line 194, however it could be a null pointer.
https://github.com/radareorg/radare2/blob/533aeeb6a31b1f8b4fc7f028df77bbdb62581322/libr/main/rasm2.c#L194
## Log File
```
=================================================================
==19376==ERROR: AddressSanitizer: SEGV on unknown address 0x00000000001a (pc 0x7ffff7e607ec bp 0x7fffffffe480 sp 0x7fffffffdd70 T0)
==19376==The signal is caused by a READ memory access.
==19376==Hint: address points to the zero page.
    #0 0x7ffff7e607ec in rarch2_list /AFLFI/radare2/libr/main/rasm2.c:194:10
    #1 0x7ffff7e5d86b in r_main_rasm2 /AFLFI/radare2/libr/main/rasm2.c:891:3
    #2 0x7ffff7c04d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #3 0x7ffff7c04e3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f) (BuildId: 69389d485a9793dbe873f0ea2c93e02efaa9aa3d)
    #4 0x5555555725b4 in _start (/AFLFI/radare2/binr/rasm2/rasm2+0x1e5b4) (BuildId: de5cd6211bd1e0fef359188b11fb03629176aab5)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /AFLFI/radare2/libr/main/rasm2.c:194:10 in rarch2_list
==19376==ABORTING
```

**Comment by trufae** [comment]
Nice catch. We are one plugin away to move into the arch to perform a lot of cleanup of those checks. But its good to have proper checks here. Thanks!

**Comment by Pikachu1412** [comment]
#21959
