### ISSUE TITLE
r_log NULL pointer deref on macOS

### ISSUE THREAD

**Issue by terorie** [radareorg/radare2#22468]
## Environment

Latest master (4d3ff5ff214123d692582a48b0e3a4f04a96f08c as of now)

## Description

The following will attempt to dereference a NULL pointer in r_core via the cbcore log callback.

```c
R_LOG_INFO ("%s", "");
```

This is a bug in r_core.

It happens because a call to `strdup (NULL)`. Presumably not an issue on some POSIX environments, but it crashes on macOS. 

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==19924==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00010c219b70 bp 0x7ff7b9a1b1b0 sp 0x7ff7b9a1b1b0 T0)
==19924==The signal is caused by a READ memory access.
==19924==Hint: address points to the zero page.
    #0 0x10c219b70 in __sanitizer::internal_strlen(char const*)+0x10 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0xf9b70)
    #1 0x10c1f2fee in strdup+0x3e (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0xd2fee)
    #2 0x10794b847 in cbcore core.c:3043
    #3 0x1066b5244 in r_log_vmessage log.c:147
    #4 0x1066b64da in r_log_message log.c:219
    #5 0x1064ede1f in test_r_log test_util.c:235
    #6 0x1064ee0f7 in all_tests test_util.c:249
    #7 0x1064ee188 in main test_util.c:254
    #8 0x7ff805f3c41e in start+0x76e (dyld:x86_64+0xfffffffffff6e41e)

==19924==Register values:
rax = 0xffffffffffffffff  rbx = 0x0000000000000000  rcx = 0x0000100000000000  rdx = 0x0000000000000000  
rdi = 0x0000000000000000  rsi = 0x0000000000000000  rbp = 0x00007ff7b9a1b1b0  rsp = 0x00007ff7b9a1b1b0  
 r8 = 0x00000ffef7343754   r9 = 0x0000000000000000  r10 = 0x00000000f1f1f100  r11 = 0x0000000000000000  
r12 = 0x00007ff7b9a1c478  r13 = 0x00007ff7b9a1c4b0  r14 = 0x00007ff7b9a1c4c0  r15 = 0x00007ff7b9a1c340  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0xf9b70) in __sanitizer::internal_strlen(char const*)+0x10
==19924==ABORTING
test_r_log zsh: abort      build/test/unit/test_util
```

**Comment by terorie** [comment]
@radare I'm going to work on a regression test and fix.
