### ISSUE TITLE
git.5.8.8-946-gffd0573fc8 has heap-buffer-overflow at /radare2/shlr/java/code.c:164:61 in java_print_opcode

### ISSUE THREAD

**Issue by gandalf4a** [radareorg/radare2#22523]
This vulnerability is a previous bypass of this "https://github.com/radareorg/radare2/commit/1bdda93e348c160c84e30da3637acef26d0348de" fix.

# Environment
```
$  r2  -v
radare2 5.8.9 31617 @ linux-x86-64
birth: git.5.8.8-946-gffd0573fc8 2023-12-08__13:40:06
commit: ffd0573fc82ebe8a275e3c74af19cfa8407b3b20
options: gpl asan -O1 cs:5 cl:2 make

$ git show
commit ffd0573fc82ebe8a275e3c74af19cfa8407b3b20 (HEAD -> master, origin/master, origin/HEAD)
Author: pancake <pancake@nopcode.org>
Date:   Thu Dec 7 21:17:53 2023 +0100

$ uname -a
Linux gandalf-ThinkPad-T14-Gen-3 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

# Asan
```
/home/gandalf/fuzz/fuzzing_radare2/out_radare2/default/crashes/id:000090,sig:06,src:047848,time:1552482672,execs:4147672,op:havoc,rep:14
[33mINFO:[0m Analyze all flags starting with sym. and entry0 (aa)
[33mINFO:[0m Analyze imports (af@@@i)
[35mWARN:[0m set your favourite calling convention in `e anal.cc=?`
[33mINFO:[0m Analyze symbols (af@@@s)
[33mINFO:[0m Recovering variables
[33mINFO:[0m Analyze all functions arguments/locals (afva@@@F)
[2K
[33mINFO:[0m Analyze function calls (aac)
[33mINFO:[0m Analyze len bytes of instructions for references (aar)
[33mINFO:[0m Finding and parsing C++ vtables (avrr)
[33mINFO:[0m Analyzing methods
[33mINFO:[0m Finding xrefs in noncode section (e anal.in=io.maps.x)
[33mINFO:[0m Emulate functions to find computed references (aaef)
=================================================================
==1800101==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200009c132 at pc 0x7fcd08e38114 bp 0x7ffcd3460010 sp 0x7ffcd3460008
READ of size 1 at 0x60200009c132 thread T0
    #0 0x7fcd08e38113 in java_print_opcode /home/gandalf/fuzz/radare2/shlr/java/code.c:164:61
    #1 0x7fcd08e3982e in r_java_disasm /home/gandalf/fuzz/radare2/shlr/java/code.c:309:10
    #2 0x7fcd086d7bf9 in decode /home/gandalf/fuzz/radare2/libr/arch/p/java/plugin.c:215:15
    #3 0x7fcd077690f7 in r_arch_decode /home/gandalf/fuzz/radare2/libr/arch/arch.c:320:9
    #4 0x7fcd04e7eb59 in r_anal_op /home/gandalf/fuzz/radare2/libr/anal/op.c:186:8
    #5 0x7fcd0bb10e97 in r_core_anal_esil /home/gandalf/fuzz/radare2/libr/core/canal.c:5738:8
    #6 0x7fcd0b57e9ac in cmd_anal_all /home/gandalf/fuzz/radare2/libr/core/./cmd_anal.inc.c:13803:6
    #7 0x7fcd0b2733a7 in cmd_anal /home/gandalf/fuzz/radare2/libr/core/./cmd_anal.inc.c:14924:8
    #8 0x7fcd0b580816 in r_core_cmd_call /home/gandalf/fuzz/radare2/libr/core/cmd.c:6353:9
    #9 0x7fcd0b580816 in cmd_anal_all /home/gandalf/fuzz/radare2/libr/core/./cmd_anal.inc.c:13659:7
    #10 0x7fcd0b2733a7 in cmd_anal /home/gandalf/fuzz/radare2/libr/core/./cmd_anal.inc.c:14924:8
    #11 0x7fcd0cdba5b7 in perform_analysis /home/gandalf/fuzz/radare2/libr/main/radare2.c:499:2
    #12 0x7fcd0cd96ddf in r_main_radare2 /home/gandalf/fuzz/radare2/libr/main/radare2.c:1727:4
    #13 0x55bc411f5a7a in main /home/gandalf/fuzz/radare2/binr/radare2/radare2.c:118:9
    #14 0x7fcd0ca29d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #15 0x7fcd0ca29e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #16 0x55bc4113d334 in _start (/home/gandalf/fuzz/radare2/binr/radare2/radare2+0x1e334)

0x60200009c132 is located 0 bytes to the right of 2-byte region [0x60200009c130,0x60200009c132)
allocated by thread T0 here:
    #0 0x55bc411bdead in __interceptor_malloc /home/build-user/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:129:3
    #1 0x7fcd0cf6c4bd in r_mem_dup /home/gandalf/fuzz/radare2/libr/util/mem.c:306:12

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/gandalf/fuzz/radare2/shlr/java/code.c:164:61 in java_print_opcode
Shadow bytes around the buggy address:
  0x0c048000b7d0: fa fa 00 01 fa fa 00 00 fa fa 00 01 fa fa 00 00
  0x0c048000b7e0: fa fa 00 00 fa fa 00 01 fa fa 04 fa fa fa fd fd
  0x0c048000b7f0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c048000b800: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fa
  0x0c048000b810: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
=>0x0c048000b820: fa fa fd fa fa fa[02]fa fa fa fa fa fa fa fa fa
  0x0c048000b830: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000b840: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000b850: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000b860: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000b870: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1800101==ABORTING
```

# Reproduce
```
r2 -A -q poc_file
```
 
# poc_file
https://github.com/gandalf4a/crash_report/blob/main/radare2/hbo_164

# Credit
```
Gandalf4a of PKU-Changsha Institute for Computing and Digital Economy
```

**Comment by trufae** [comment]
Thanks for reporting!, i have fixed the bug in master and imported the reproducer into the crash testsuite!
